### PR TITLE
Colorize mentioned username and link to user profile

### PR DESCRIPTION
**Pull request by tayandenga**
As requested previously in here:
https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/189561
https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/177531
https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/183871
https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/182861
https://www.phpbb.com/customise/db/extension/simple_mentions/support/topic/179466

### CODE REVIEW

**Comment by paul999** [comment]
The problem with this implementation (And also directly the reason why it wasn't implemented at first) is that load_user_by_username runs a query for each call: https://github.com/phpbb/phpbb/blob/master/phpBB/phpbb/user_loader.php#L104 And you are running this method within a loop, which is actually called again within a loop (Namely the postrow loop from viewtopic). So for each mentioned user you run a extra query. This is not something which is acceptable performance wise, and it will also not be accepted in the CDB. So unless you come up with a solution which does one query extra for viewtopic, I am unable to accept it.

**Comment by tayandenga** [comment]
Are you sure? Aren't DBAL queries ACM-cached by default?

**Comment by paul999** [comment]
No, they are not cached by default. Only when the second parameter is set to a integer it is cached.
And even then it might be a huge amount of cache calls, especially when the query is not in cache at all.

**Comment by tayandenga** [comment]
Indeed, I haven't digged much about phpBB's cache before. Ok, I have one idea for now, but that's not most clever one and probably doesn't match the extension coding guidelines. The only way to cache the user right now is to store the formatted username for current page request in $GLOBALS.

**Comment by paul999** [comment]
Using globals is indeed a no go solution :) The best way how to solve it is to first try to get a list of all username's mentioned in the topic, and once you have that list, actually query it. This will result in 1 query to get the user_ids, and probarbly 1 query to get the user data using the user_loader.

**Comment by tayandenga** [comment]
It's still somehow necessary to store the username collection somewhere before querying and replacing them in posts ;) I don't see other solution right now.

**Comment by paul999** [comment]
Yes, you will first need to get a list of the usernames, and from there do two queries. The current solution is not acceptable due to performance reasons.

**Comment by Neustradamus** [comment]
Any progress on it?
- https://github.com/paul999/mention/pull/58
- https://github.com/paul999/mention/pull/57

**Comment by paul999** [comment]
Please stop replying to 5 year old issues.

**Pull request closed without merging**
