### PR TITLE
Update Arabic Translation

### PR DESCRIPTION
**Pull request by alhitary**
Dear Sir,

Plz accept Arabic Update Translation

### CODE REVIEW

**Comment by paul999** [comment]
Please fix the merge conflicts

**Comment by alhitary** [comment]
Sorry Sir,
I wish I could fix the conflict this time
I'm not good in using github by the way

**Comment by Neustradamus** [comment]
@alhitary: Translations are good now?

**Comment by paul999** [comment]
Please stop replying to 5 year old issues.

**Pull request closed without merging**
